# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ekart-container
          image: nivisha/ekart:latest
          ports:
            - containerPort: 8070  # Must match the port inside the container
          imagePullPolicy: Always
