apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ekart-container
          image: nivisha/my-app:latest  
          ports:
            - containerPort: 8070  
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"  # Minimum memory requested by the container
              cpu: "500m"      # Minimum CPU requested by the container
            limits:
              memory: "512Mi"  # Maximum memory the container can use
              cpu: "1"         # Maximum CPU the container can use
