apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ekart
          image: nivisha/ekart:latest  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070  # Port your application listens on

---
apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc  # Name of the service
spec:
  selector:
    app: ekart  # Should match the label in your Deployment
  ports:
    - protocol: "TCP"
      port: 80      # Port to expose externally
      targetPort: 8070  # Port on the container
  type: LoadBalancer  # Expose the service externally
