apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8070       
      targetPort: 8070 
      nodePort: 30007  
