apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart
  type: NodePort  # Expose this service as a NodePort
  ports:
    - protocol: TCP
      port: 8070       # The port exposed by the service
      targetPort: 8070 # The port inside the container
      nodePort: 30007  # Optional: Use a fixed NodePort (optional but recommended)
